name: Continous build - build and test on every push

on: push

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          submodules: true

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build with Ant
        run: ant compile

      - name: Test with Ant
        run: ant test
